import os 

BASE_DIR = os.getcwd()

COMPUTADOR_DIAX = False

if COMPUTADOR_DIAX:
    DIRETORIO_PRINCIPAIS_ACOES = r'E:\DADOS_FINANCEIROS\DADOS\Database_PrincipaisAcoes'
    DIRETORIO_PROFIT_AJUSTADO_COM_SPLIT = r'E:\DADOS_FINANCEIROS\Profit\Database_NAS'
    DIRETORIO_PROFIT_SEM_AJUSTE = r'E:\DADOS_FINANCEIROS\Profit\Database_ProfitDiario'
    DIRERORIO_ALERTADOR = r'E:\DADOS_FINANCEIROS\DADOS\Database_Alertador' 
else:
    DIRETORIO_PRINCIPAIS_ACOES = r'E:\DADOS_FINANCEIROS\DADOS\Database_PrincipaisAcoes'
    DIRETORIO_PROFIT_AJUSTADO_COM_SPLIT = r'E:\DADOS_FINANCEIROS\Profit\Database_NAS'
    DIRETORIO_PROFIT_SEM_AJUSTE = r'E:\DADOS_FINANCEIROS\Profit\Database_ProfitDiario'
    DIRERORIO_ALERTADOR = r'E:\DADOS_FINANCEIROS\DADOS\Database_Alertador' 


PATH_ARQUIVO_FERIADOS = os.path.join(BASE_DIR, 'feriados-b3.json')
DIRETORIO_LOG = os.path.join(BASE_DIR, 'log', 'log-desempenho-alertador.txt')